/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication20;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author MildReed Zaarv'
 */
public class ExamenAlumno extends javax.swing.JFrame {
    public PreguntasA pa;
    public ExamenAlumno() {
        initComponents();
        pa=new PreguntasA();
    }
    public void setNombre(String n){
        pa.setNombre(n);
        
    }
    public void setMatricula(String n){
        pa.setMatricula(n);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoExamen = new javax.swing.ButtonGroup();
        Prueba = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        Cancelar = new javax.swing.JButton();
        Aceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ComboMaterias = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        ComboCarrera = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        semestre = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("APLICAR EXAMEN");

        tipoExamen.add(Prueba);
        Prueba.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        Prueba.setText("Prueba");
        Prueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PruebaActionPerformed(evt);
            }
        });

        tipoExamen.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jRadioButton2.setText("Real");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        Cancelar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        Cancelar.setForeground(new java.awt.Color(0, 102, 102));
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        Aceptar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        Aceptar.setForeground(new java.awt.Color(0, 102, 102));
        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        jLabel1.setText("Materia");

        ComboMaterias.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        ComboMaterias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TALLER DE DIBUJO", "FILOSOFÍA", "HISTORIA", "ESTRUCTURAS", "MATERIALES", "DISEÑO" }));
        ComboMaterias.setSelectedItem(ComboCarrera);
        ComboMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboMateriasActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        jLabel3.setText("Carrera");

        ComboCarrera.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        ComboCarrera.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ARQUITECTURA", "DERECHO", "FISIOTERAPIA", "GASTRONOMÍA", "INGENIERÍA AMBIENTAL", "INGENIERÍA CIVIL", "INGENIERÍA INDUSTRIAL", "INGENIERÍA EN ELECTRÓNICA", "NEGOCIOS" }));
        ComboCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCarreraActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        jLabel6.setText("Semestre");

        semestre.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        semestre.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));
        semestre.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                semestreStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel2.setText("Tipo de examen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Prueba)
                        .addGap(51, 51, 51)
                        .addComponent(jRadioButton2))
                    .addComponent(semestre, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(Aceptar)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ComboCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(semestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Prueba)
                    .addComponent(jRadioButton2)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar)
                    .addComponent(Aceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void asignar(){
         Integer a=Integer.parseInt(String.valueOf(semestre.getValue()));
       if(a==1){
           String n=String.valueOf(ComboCarrera.getSelectedItem());
        switch (n){
            case "ARQUITECTURA":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("TALLER DE DIBUJO I");
                ComboMaterias.addItem("FILOSOFÍA");
                ComboMaterias.addItem("TEORÍA DE ARQUITECTURA I");
                ComboMaterias.addItem("ESTRUCTURAS");
                ComboMaterias.addItem("MATERIALES");
                ComboMaterias.addItem("DISEÑO");
                break;
            case "DERECHO":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("DERECHO ROMANO I");
                ComboMaterias.addItem("TEORÍAS DE ESTADO");
                ComboMaterias.addItem("SISTEMAS JURÍDICOS");
                ComboMaterias.addItem("DERECHOS HUMANOS");
                ComboMaterias.addItem("FILOSOFÍA");
                ComboMaterias.addItem("SOCIOLOGÍA JURÍDICA");
                break;
            case "FISIOTERAPIA":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("FISIOLOGÍA DEL EJERCICIO");
                ComboMaterias.addItem("DISCAPACIDAD Y SOCIEDAD");
                ComboMaterias.addItem("KINESIOLOGÍA");
                ComboMaterias.addItem("BIOMECÁNICA");
                ComboMaterias.addItem("FUNDAMENTOS DE EMBRIOLOGÍA");
                ComboMaterias.addItem("ANATOMOFISIOLOGÍA HUMANA");
                break;
            case "INGENIERÍA CIVIL":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("QUÍMICA PARA LA INGENIERÍA");
                ComboMaterias.addItem("PROGRAMACIÓN");
                ComboMaterias.addItem("CÁLCULO");
                ComboMaterias.addItem("ÁLGEBRA");
                ComboMaterias.addItem("FÍSICA");
                break;
            case "INGENIERÍA INDUSTRIAL":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("PROCESOS Y EXPRESIÓN");
                ComboMaterias.addItem("ÁLGEBRA SUPERIOR");
                ComboMaterias.addItem("CÁLCULO");
                ComboMaterias.addItem("FÍSICA");
                ComboMaterias.addItem("QUÍMICA");
                break;
            case "GASTRONOMÍA":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("ADMINISTRACIÓN");
                ComboMaterias.addItem("NUTRICIÓN Y PRODUCTOS");
                ComboMaterias.addItem("COMERCIALIZACIÓN");
                ComboMaterias.addItem("RELACIONES PÚBLICAS");
                break;
            case "INGENIERÍA AMBIENTAL":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("QUÍMICA ORGÁNICA");
                ComboMaterias.addItem("CÁLCULO");
                ComboMaterias.addItem("ÁLGEBRA LINEAL");
                ComboMaterias.addItem("BIOQUÍMICA");
                ComboMaterias.addItem("FÍSICA");
                ComboMaterias.addItem("ANTROPOLOGÍA");
                break;
            case "INGENIERÍA EN ELECTRÓNICA":
                
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("ÁLGEBRA SUPERIOR");
                ComboMaterias.addItem("PROGRAMACIÓN");
                ComboMaterias.addItem("LA PERSONA Y SU PROCESO F.");
                ComboMaterias.addItem("INTRODUCCIÓN A LA INGENIERÍA");
                ComboMaterias.addItem("COMUNICACIÓN PROFESIONAL");
                ComboMaterias.addItem("METROLOGÍA E INSTRUMENTACIÓN");
                break;
            case "NEGOCIOS":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("CONTABILIDAD");
                ComboMaterias.addItem("ECONOMÍA");
                ComboMaterias.addItem("TIC'S");
                ComboMaterias.addItem("ARTE, HISTORIA Y CULTURA");
                ComboMaterias.addItem("MATEMÁTICAS");
                ComboMaterias.addItem("FILOSOFÍA");
                break;
         }
           
       }else if(a==2){
        String n=String.valueOf(ComboCarrera.getSelectedItem());
        switch (n){
            case "ARQUITECTURA":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("TEORÍA DE ARQUITECTURA II");
                ComboMaterias.addItem("TALLER DE DIBUJO II");
                ComboMaterias.addItem("MATEMÁTICAS APLICADAS");
                ComboMaterias.addItem("SISTEMAS ESTRUCTURALES");
                ComboMaterias.addItem("ARQUITECTURA EN MÉXICO.");
                break;
            case "DERECHO":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("DERECHO ROMANO II");
                ComboMaterias.addItem("TEORÍA DEL DERECHO");
                ComboMaterias.addItem("METODOLOGÍA JURÍDICA");
                ComboMaterias.addItem("TEORÍA DE LA CONSTITUCIÓN");
                ComboMaterias.addItem("ACTO JURÍDICO Y PERSONAS");
                ComboMaterias.addItem("SOCIOLOGÍA JURÍDICA");
                break;
            case "FISIOTERAPIA":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("BIOLOGÍA MOLECULAR");
                ComboMaterias.addItem("BIOLOGÍA CELULAR");
                ComboMaterias.addItem("FUNCIÓN MUSCULAR");
                ComboMaterias.addItem("MEDICAMENTOS");
                ComboMaterias.addItem("APRENDIZAJE BASADO EN PROBLEMAS");
                break;
            case "INGENIERÍA CIVIL":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("PROGRAMACIÓN");
                ComboMaterias.addItem("ESTÁTICA");
                ComboMaterias.addItem("CÁLCULO VECTORIAL");
                ComboMaterias.addItem("ÁLGEBRA LINEAL");
                ComboMaterias.addItem("FÍSICA II");
                break;
            case "INGENIERÍA INDUSTRIAL":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("FILOSOFÍA");
                ComboMaterias.addItem("ECONOMÍA");
                ComboMaterias.addItem("CÁLCULO");
                ComboMaterias.addItem("ÁLGEBRA");
                ComboMaterias.addItem("MERCADOTECNIA");
                break;
            case "GASTRONOMÍA":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("SANIDAD AMBIENTAL");
                ComboMaterias.addItem("BIOQUÍMICA");
                ComboMaterias.addItem("EPIDEMIOLOGÍA");
                ComboMaterias.addItem("RELACIONES PÚBLICAS");
                break;
            case "INGENIERÍA AMBIENTAL":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("LABORATORIO");
                ComboMaterias.addItem("CÁLCULO VECTORIAL");
                ComboMaterias.addItem("ÁLGEBRA LINEAL");
                ComboMaterias.addItem("TERMODINÁMICA");
                ComboMaterias.addItem("ECUACIONES DIFERENCIALES");
                ComboMaterias.addItem("FÍSICA");
                ComboMaterias.addItem("ANTROPOLOGÍA");
                break;
            case "INGENIERÍA EN ELECTRÓNICA":
                
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("ÁLGEBRA LINEAL");
                ComboMaterias.addItem("CÁLCULO");
                ComboMaterias.addItem("ANÁLISIS DE CIRCUITOS");
                ComboMaterias.addItem("CIRCUITOS LÓGICOS");
                ComboMaterias.addItem("ANTROPOLOGÍA");
                ComboMaterias.addItem("PROGRAMACIÓN");
                break;
            case "NEGOCIOS":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("ECONOMETRÍA");
                ComboMaterias.addItem("SISTEMAS TRIBUTARIOS");
                ComboMaterias.addItem("ESTADÍSTICA");
                ComboMaterias.addItem("MATEMÁTICAS FINANCIERAS");
                ComboMaterias.addItem("ANTROPOLOGÍA");
                break;
         }
       }else if(a==3){
           String n=String.valueOf(ComboCarrera.getSelectedItem());
        switch (n){
            case "ARQUITECTURA":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("ARQUITECTURA, AMBIENTE y CIUDAD");
                ComboMaterias.addItem("ARQUITECTURA MESOAMERICANA");
                ComboMaterias.addItem("TEORÍA DE LA ARQUITECTURA III");
                ComboMaterias.addItem("INSTALACIONES I");
                ComboMaterias.addItem("SISTEMAS ESTRUCTURALES III");
                ComboMaterias.addItem("EXTENSIÓN UNIVERSITARIA");
                break;
            case "DERECHO":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("BIENES Y DERECHOS REALES");
                ComboMaterias.addItem("DELITOS EN PARTICULAS");
                ComboMaterias.addItem("DERECHO CONSTITUCIONAL");
                ComboMaterias.addItem("SISTEMAS JURÍDICOS");
                ComboMaterias.addItem("TEORÍA DEL PROCESO");
                ComboMaterias.addItem("TEORÍA ECONÓMICA");
                break;
            case "FISIOTERAPIA":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("FISIOLOGÍA");
                ComboMaterias.addItem("BIOMEDICINA");
                ComboMaterias.addItem("COMPUTACIÓN");
                ComboMaterias.addItem("HISTOLOGIA");
                ComboMaterias.addItem("FILOSOFÍA");
                ComboMaterias.addItem("FARMACOLOGÍA");
                break;
            case "INGENIERÍA CIVIL":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("ELECTRICIDAD Y MAGNETISMO");
                ComboMaterias.addItem("TEORÍA DE CONTROL");
                ComboMaterias.addItem("DINÁMICA");
                ComboMaterias.addItem("MATEMÁTICAS DISCRETAS");
                ComboMaterias.addItem("ECUACIONES DIFERENCIALES");
                break;
            case "INGENIERÍA INDUSTRIAL":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("ECUACIONES DIFERENCIALES");
                ComboMaterias.addItem("ECONOMÍA II");
                ComboMaterias.addItem("CÁLCULO VECTORIAL");
                ComboMaterias.addItem("ECONOMETRÍA");
                ComboMaterias.addItem("ANÁLISIS NUMÉRICO");
                break;
            case "GASTRONOMÍA":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("GASTRONOMÍA MEXICANA");
                ComboMaterias.addItem("BIOQUÍMICA METABÓLICA");
                ComboMaterias.addItem("NUTRICIÓN HUMANA");
                ComboMaterias.addItem("RELACIONES PÚBLICAS");
                break;
            case "INGENIERÍA AMBIENTAL":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("LABORATORIO");
                ComboMaterias.addItem("CÁLCULO");
                ComboMaterias.addItem("ÁLGEBRA LINEAL");
                ComboMaterias.addItem("BIOQUÍMICA");
                ComboMaterias.addItem("TERMODINÁMICA");
                ComboMaterias.addItem("ECUACIONES DIFERENCIALES");
                ComboMaterias.addItem("FÍSICA");
                ComboMaterias.addItem("ANTROÓLOGÍA");
                break;
            case "INGENIERÍA EN ELECTRÓNICA":
                
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("CÁLCULO VECTORIAL");
                ComboMaterias.addItem("ECUACIONES DIFERENCIALES");
                ComboMaterias.addItem("ANÁLISIS DE CIRCUITOS II");
                ComboMaterias.addItem("DISEÑO LÓGICO");
                ComboMaterias.addItem("DISPOSITIVOS SEMICONDUCTORES");
                ComboMaterias.addItem("SÍNTESIS DE CIRCUITOS LÓGICOS");
                break;
            case "NEGOCIOS":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("CONTABILIDAD II");
                ComboMaterias.addItem("ECONOMÍA II");
                ComboMaterias.addItem("ARTE, HISTORIA Y CULTURA");
                ComboMaterias.addItem("MATEMÁTICAS");
                ComboMaterias.addItem("EL HOMBRE UN SER SOCIAL");
                break;
         }
       }else if(a==4){
           String n=String.valueOf(ComboCarrera.getSelectedItem());
       switch (n){
            case "ARQUITECTURA":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("TALLER DE DIBUJO");
                ComboMaterias.addItem("FILOSOFÍA");
                ComboMaterias.addItem("HISTORIA");
                ComboMaterias.addItem("ESTRUCTURAS");
                ComboMaterias.addItem("MATERIALES");
                ComboMaterias.addItem("DISEÑO");
                break;
            case "DERECHO":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("DERECHO CIVIL");
                ComboMaterias.addItem("TEORÍAS DE ESTADO");
                ComboMaterias.addItem("SISTEMAS JURÍDICOS");
                ComboMaterias.addItem("DERECHOS HUMANOS");
                ComboMaterias.addItem("FiLOSOFÍA");
                ComboMaterias.addItem("SOCIOLOGÍA JURÍDICA");
                break;
            case "FISIOTERAPIA":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("ANATOMÍA");
                ComboMaterias.addItem("FISIOLOGÍA");
                ComboMaterias.addItem("BIOQUÍMICA");
                ComboMaterias.addItem("BIOMECÁNICA");
                ComboMaterias.addItem("COMPUTACIÓN");
                ComboMaterias.addItem("HISTOLOGIA");
                ComboMaterias.addItem("FILOSOFÍA");
                ComboMaterias.addItem("FARMACOLOGÍA");
                break;
            case "INGENIERÍA CIVIL":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("TERMODINÁMICA");
                ComboMaterias.addItem("PROBABILIDAD Y ESTADISTICA");
                ComboMaterias.addItem("RESISTENCIA DE MATERIALES");
                ComboMaterias.addItem("HIDRÁULICA");
                ComboMaterias.addItem("COMUNICACIÓN PROFESIONAL");
                break;
            case "INGENIERÍA INDUSTRIAL":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("ELECTRICIDAD INDUSTRIAL");
                ComboMaterias.addItem("ECUACIONES DIFERENCIALES");
                ComboMaterias.addItem("METROLOGÍA");
                ComboMaterias.addItem("ESTUDIO DEL TRABAJO");
                ComboMaterias.addItem("MÉTODOS ESTADÍSTICOS");
                break;
            case "GASTRONOMÍA":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("COCINA ITALIANA");
                ComboMaterias.addItem("COCINA FRANCESA");
                ComboMaterias.addItem("REPOSTERÍA");
                ComboMaterias.addItem("VINICULTURA");
                break;
            case "INGENIERÍA AMBIENTAL":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("SISTEMAS DE LA TIERRA");
                ComboMaterias.addItem("QUÍMICA INORGÁNICA");
                ComboMaterias.addItem("FLUJO DE FLUIDOS");
                ComboMaterias.addItem("QUÍMICA ANALÍTICA");
                ComboMaterias.addItem("BALANCES DE MATERIA Y ENERGÍA");
                break;
            case "INGENIERÍA EN ELECTRÓNICA":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("TEORÍA DE CONTROL");
                ComboMaterias.addItem("ANÁLISIS DE SEÑALES");
                ComboMaterias.addItem("CIRCUITOS INTEGRADOS LINEALES");
                ComboMaterias.addItem("SISTEMAS MECATRÓNICOS");
                ComboMaterias.addItem("DISEÑO ASISTIDO POR COMPUTADORA");
                ComboMaterias.addItem("EL HOMBRE UN SER SOCIAL");
                break;
            case "NEGOCIOS":
                ComboMaterias.removeAllItems();
                ComboMaterias.addItem("GEOECONOMÍA");
                ComboMaterias.addItem("LOGÍSTICA Y TRANSPORTE");
                ComboMaterias.addItem("MARCO JURÍDICO DE LA EMPRESA");
                ComboMaterias.addItem("MÉTODOS ESTADÍSCICOS");
                break;
         }
       }
     }
    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed
//   
    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
           
        if(tipoExamen.isSelected(null)){
            JOptionPane.showMessageDialog(this, "Seleccione el tipo de examen.", "Mensaje", 1, null);
        }else{
            pa.setCarrera(String.valueOf(String.valueOf(ComboCarrera.getSelectedItem())));
            pa.setMateria(String.valueOf(ComboMaterias.getSelectedItem()));
            pa.setSemestre(Integer.parseInt(String.valueOf(semestre.getValue())));
            String t="";{
            if(Prueba.isSelected()){
                t="Prueba";
            }else{
                t="Real";
            }
        }
            pa.setTipoExamen(t);
        ResponderExamen re=new ResponderExamen();
        re.setpgt(pa);
        re.setVisible(true);
        setVisible(false);
        }
    }//GEN-LAST:event_AceptarActionPerformed
    
    private void ComboMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboMateriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboMateriasActionPerformed

    private void ComboCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCarreraActionPerformed
        asignar();
    }//GEN-LAST:event_ComboCarreraActionPerformed

    private void semestreStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_semestreStateChanged
        asignar();
    }//GEN-LAST:event_semestreStateChanged

    private void PruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PruebaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PruebaActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
       setVisible(false);
    }//GEN-LAST:event_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamenAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamenAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamenAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamenAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamenAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JComboBox ComboCarrera;
    private javax.swing.JComboBox ComboMaterias;
    private javax.swing.JRadioButton Prueba;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSpinner semestre;
    private javax.swing.ButtonGroup tipoExamen;
    // End of variables declaration//GEN-END:variables
}
