/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Biblioteca1;

import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MildReed Zaarv'
 */
public class IngresarUsuario extends javax.swing.JFrame {

    private ControllerUsuario controllerUsuario;
    private ControllerLibros controllerLibros;
    private PantallaAdministrador pAdministrador;
    private UsuarioAlumno uAlumno;
    private String tipoUsuario;
    private VerPrestamos verPrest;
    public IngresarUsuario() {
        pAdministrador=new PantallaAdministrador();
        verPrest=new VerPrestamos(this,true);
        uAlumno=new UsuarioAlumno();
        initComponents();
    }
    public void setControllerUsuario(ControllerUsuario cont){
        controllerUsuario=cont;
    }
    public void setControllerLibros(ControllerLibros cl){
        controllerLibros=cl;
    }
    public void settipoUsuario(String s){
        tipoUsuario=s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAceptar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsuario)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnAceptar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
       if(txtContraseña.getText().length()!=0){
          if(buscarUsuario()){
            if(tipoUsuario.equalsIgnoreCase("Administrador")){
                pAdministrador.setControllerUsuario(controllerUsuario);
                pAdministrador.setControllerLibros(controllerLibros);
                pAdministrador.setVisible(true);
            }else{
                verPrest.setContLibros(controllerLibros);
                verPrest.setContUsuario(controllerUsuario);
                verPrest.setuAlumno(uAlumno);
                verPrest.setVisible(true);
            }
        }
       }else{
        JOptionPane.showMessageDialog(this, "Ingrese la contraseña", "Contraseña", 1,null );   
       }
       txtContraseña.setText("");
       txtUsuario.setText("");
    }//GEN-LAST:event_btnAceptarActionPerformed
    public  String convertToMD5(final String md5) throws UnsupportedEncodingException{
        StringBuffer sb=null;
        try{
            final java.security.MessageDigest md= java.security.MessageDigest.getInstance("MD5");
            final byte[] array=md.digest(md5.getBytes("UTF-8"));
            sb=new StringBuffer();
            for (int i = 0; i <array.length; i++) {
                sb.append(Integer.toHexString((array[i] & 0xFF) | 0x100).substring(1, 3));
            }return sb.toString();
        }catch(final java.security.NoSuchAlgorithmException e){
            
        }return sb.toString();
    }
    /**
     * @param args the command line arguments
     */
    public boolean buscarUsuario(){
        if(tipoUsuario.equalsIgnoreCase("Administrador")){
        Object[] usuarios=controllerUsuario.ObtenerUsuarios();
        for (int i = 0; i < usuarios.length; i++) {
            Usuario u1=(Usuario)usuarios[i];
            if(u1.getUsuario().equalsIgnoreCase(txtUsuario.getText())){
                try {
                    if(u1.getContraseña().equalsIgnoreCase(convertToMD5(txtContraseña.getText()))){
//                        usuario=u1;
                        txtContraseña.setText("");
                        txtUsuario.setText("");
                        setVisible(false);
                        return true;
                        
                    }else{
                        JOptionPane.showMessageDialog(this, "Contraseña incorrecta", "ERROR", 0,null );
                        txtContraseña.setText("");
                        return false;
                    }
                } catch (UnsupportedEncodingException ex) {
                    Logger.getLogger(IngresarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            }
            
        } JOptionPane.showMessageDialog(this, "Usuario no encontrado", "NOT FOUND", 0,null );
        }else{
             Object[] alumnos=controllerUsuario.ObtenerAlumnos();
        for (int i = 0; i < alumnos.length; i++) {
            UsuarioAlumno u1=(UsuarioAlumno)alumnos[i];
            if(u1.getUsuario().equalsIgnoreCase(txtUsuario.getText())){
                try {
                    if(u1.getContraseña().equalsIgnoreCase(convertToMD5(txtContraseña.getText()))){
                      uAlumno=u1;
                        txtContraseña.setText("");
                        txtUsuario.setText("");
                        setVisible(false);
                        return true;
                        
                    }else{
                        JOptionPane.showMessageDialog(this, "Contraseña incorrecta", "ERROR", 0,null );
                        txtContraseña.setText("");
                        return false;
                    }
                } catch (UnsupportedEncodingException ex) {
                    Logger.getLogger(IngresarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            }
            
        } JOptionPane.showMessageDialog(this, "Usuario no encontrado", "NOT FOUND", 0,null );
        }
        txtUsuario.setText("");
        txtContraseña.setText("");
        return false;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
